"""Does the rendered page still map back to the document?

cv_map reads the Typst source RenderCV compiled to work out where every
section and entry landed, which is what makes the preview clickable. It is the
one part of the app that depends on the shape of somebody else's generated
code, and when that shape moves it does not raise anywhere the user can see:
the probes go in wrong, the map comes back empty, and the page is a picture.

Two ways it has actually broken, both of them silent:

  * A probe inserted before a line that only closes a call. RenderCV 2.8
    indents `#regular-entry(` for an entry with no dates and closes it at
    column 0, so counting parens on column-0 lines alone saw the close without
    the open and took the next `)` for the start of an entry. `#` inside an
    argument list is a syntax error, so the whole probed document failed to
    compile and every click target on the page went with it -- on seven of the
    nine themes 2.8 ships.

  * Entries found by the blank lines between them. Before 2.8 unified the
    templates, consecutive one-line and bullet entries were written flush with
    no blank line anywhere between them, so a Skills section of four produced
    one probe and quietly stopped being clickable below the heading.

So: real Typst, captured from every theme of both shapes, checked for the
counts it should produce and for the one thing that fails the compile. No
Typst, no RenderCV, nothing to install -- the fixtures are the files
themselves, regenerated by rendering the CV in checks/typst/README.md.
"""
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import cv_map  # noqa: E402

# The CV the fixtures were rendered from, as cv_map wants it: (key, entries).
OUTLINE = [("summary", 1), ("experience", 2), ("education", 1), ("skills", 4),
           ("projects", 1), ("certifications", 2), ("publications", 1)]

fails = []


def check(name, ok, detail=""):
    print(f"  {'ok  ' if ok else 'FAIL'}  {name}" + (f"  -> {detail}" if detail else ""))
    if not ok:
        fails.append(name)


root = ROOT / "checks" / "typst"
fixtures = sorted(root.glob("*/*.typ"))
check("there are theme fixtures to read", bool(fixtures), f"{len(fixtures)} found")

for path in fixtures:
    name = f"{path.parent.name}/{path.stem}"
    source = path.read_text(encoding="utf-8")
    probed, probes = cv_map._inject(source)

    counts: dict[int, int] = {}
    for p in probes:
        if p["kind"] == "entry":
            counts[p["s"]] = counts.get(p["s"], 0) + 1
    got = [counts.get(i, 0) for i in range(len(OUTLINE))]
    want = [n for _, n in OUTLINE]
    sections = sum(1 for p in probes if p["kind"] == "section")

    check(f"{name}: one probe per section", sections == len(OUTLINE),
          f"{sections} of {len(OUTLINE)}" if sections != len(OUTLINE) else "")
    check(f"{name}: one probe per entry", got == want,
          f"got {got}, want {want}" if got != want else "")

    # The compile-breaking one, without needing Typst to say so: a probe is
    # markup and the line after a `)` or a `,` is code.
    lines = probed.splitlines()
    stray = [lines[i + 1] for i, line in enumerate(lines[:-1])
             if line.startswith(f"#{cv_map.LABEL}(")
             and lines[i + 1].lstrip()[:1] in (")", "]", "}", ",")]
    check(f"{name}: no probe lands inside a call", not stray,
          f"before {stray[0]!r}" if stray else "")

print("\nclean" if not fails else f"\n{len(fails)} failure(s)")
sys.exit(1 if fails else 0)
